version: '3.7'
services:
    app:
        image: bantenitsolutions/nginx-php-lite
        build: .
        ports:
            - '80:80'
    sut:
        image: alpine:3.18
        depends_on:
            - app
        command: /tmp/run.sh
        volumes:
            - "./run.sh:/tmp/run.sh"
