version: '3.5'
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: .
    ports:
        - '80:80'
  sut:
    image: alpine:3.18
    depends_on:
      - app
    command: chmod +x /tmp/run.sh
    volumes:
      - "./run.sh:/tmp/run.sh"