version: '3.7'
services:
    app:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        build: .
    sut:
        image: alpine:3.18
        depends_on:
            - app
        command: /tmp/run.sh
        volumes:
            - "./run.sh:/tmp/run.sh:ro"